services:
  app:
    image: twinproduction/gatus:latest
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - GATUS_CONFIG_PATH=/config
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - GATUS_LOG_LEVEL=WARN
    volumes:
      - app_config:/config
    networks:
      - default
      - proxy_apps
    depends_on:
      appconfig:
        condition: service_completed_successfully
      configsync:
        condition: service_healthy
      database:
        condition: service_healthy

  database:
    restart: unless-stopped
    image: pgautoupgrade/pgautoupgrade:latest
    volumes:
      - db_data:/var/lib/postgresql
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 1m
      timeout: 10s
      start_period: 20s
      retries: 6
    labels:
      - ofelia.restart=true
      - ofelia.enabled=true
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.schedule=0 0 1 * * *"
      - "ofelia.job-exec.${COMPOSE_PROJECT_NAME}dbbackup.command=sh -c 'pg_dumpall -U ${POSTGRES_USER} -f /var/lib/postgresql/backup.sql'"
    networks:
      - default

  sshkeygenerator:
    image: ghcr.io/hueske-digital/sshkey-generator:latest
    restart: "no"
    volumes:
      - ssh_data:/root/.ssh

  configsync:
    image: alpine/git
    healthcheck:
      test: ["CMD", "sh", "-c", "test -d /config/.git"]
      interval: 10s
      retries: 3
    depends_on:
      sshkeygenerator:
        condition: service_completed_successfully
    restart: unless-stopped
    environment:
      - GIT_REPO_URL
      - SYNC_INTERVAL
    volumes:
      - app_config:/config
      - ssh_data:/root/.ssh
    entrypoint: ["/bin/sh", "-c"]
    command: >
      "
        mkdir -p /config &&
        if [ -f /config/config.yaml ]; then
          rm -f /config/config.yaml;
        fi;
        if [ ! -d /config/.git ]; then
          git clone --depth=1 -b main ${GIT_REPO_URL} /config;
        fi;
        while true; do
          git -C /config pull origin main || echo 'Pull failed…';
          sleep ${SYNC_INTERVAL};
        done
      "

  appconfig:
    image: hairyhenderson/gomplate:alpine
    env_file:
      - .env
    volumes:
      - ./templates:/templates:ro
      - app_config:/config
    command:
      [
        "-f", "/templates/global.tpl.yaml",
        "-o", "/config/global.yaml"
      ]
    restart: "no"
    depends_on:
      configsync:
        condition: service_healthy

volumes:
  app_config:
  db_data:
  ssh_data:

networks:
  proxy_apps:
    name: proxy_apps
    external: true
  default:
